SELECT * FROM tabela_de_produtos;

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
	CASE 
		WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
		WHEN PRECO_DE_LISTA >=7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
		ELSE 'PRODUTO BARATO' 
	END AS 'STATUS PRECO' 
FROM tabela_de_produtos;

SELECT SABOR, EMBALAGEM,
	CASE 
		WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
		WHEN PRECO_DE_LISTA >=7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
		ELSE 'PRODUTO BARATO' 
	END AS 'STATUS PRECO', AVG(PRECO_DE_LISTA)  AS 'PRECO MEDIO'
FROM tabela_de_produtos
WHERE SABOR = 'Manga'
GROUP BY EMBALAGEM,
	CASE 
		WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
		WHEN PRECO_DE_LISTA >=7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
		ELSE 'PRODUTO BARATO' 
	END
ORDER BY EMBALAGEM;

SELECT * FROM tabela_de_clientes;

SELECT NOME, SEXO, (DATA_DE_NASCIMENTO) AS 'ANO NASCIMENTO',
	CASE 
		WHEN YEAR(DATA_DE_NASCIMENTO) < 1990 THEN 'VELHO'
		WHEN YEAR(DATA_DE_NASCIMENTO) BETWEEN 1990 AND 1995 THEN 'JOVEN'
        ELSE 'CRIANÇA'
	END AS 'CLASSIFICACAO'
FROM tabela_de_clientes;
