SELECT CURRENT_TIMESTAMP() AS RESULTADO;

SELECT CONCAT('O dia de hoje é: ', CURRENT_TIMESTAMP()) AS RESULTADO;

SELECT CONCAT('A data de hoje é: ', CURRENT_TIMESTAMP()) AS RESULTADO;

SELECT CONCAT('A data de hoje é: ', 
DATE_FORMAT(CURRENT_TIMESTAMP(), '%d/%m/%Y - %U')) AS RESULTADO;

SELECT SUBSTRING(CONVERT(23.3, CHAR), 1 ,1) AS RESULTADO;

SELECT CONCAT('O cliente ', TC.NOME, ' faturou ', ROUND(CAST(SUM(INF.QUANTIDADE * INF.PRECO) AS CHAR (20)), 2), ' no ano de ', CAST(YEAR(NF.DATA_VENDA) AS CHAR (20))) AS SENTENCA FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF ON NF.NUMERO = INF.NUMERO
INNER JOIN tabela_de_clientes TC ON NF.CPF = TC.CPF
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY TC.NOME, YEAR(DATA_VENDA);